//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Backup
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string FullPath { get; set; }
        public string Crc { get; set; }
        public decimal LastWriteTime { get; set; }
        public long IsNew { get; set; }
        public long DirectoryId { get; set; }
    
        public virtual Directory Directory { get; set; }
    }
}
